### ISSUE TITLE
NVme

### ISSUE THREAD

**Issue by ghost** [wmchris/DellXPS15-9560-OSX#3]
Hi , I know that the problem has been already closed but  I did all your steps even remove the patches and hotfixes but nothing is working for my toshiba 512 NVme SSD Drive.

You did this for the 9560 which is the same composent of my computer why it's not working anymore I should do any modifications to get it work ?

Thanks for your help

**Comment by krim404** [comment]
There are multiple possible issues. First: did you do the 4k fix? if no: i would highly suggest doing it. 

If you didnt do the 4k fix you really need the patches. If its still not working: most people get it working by recreating the usb stick (faulty usb stick creation, most because of using a virtual machine)

**Comment by ghost** [comment]
Hi thanks for your answer i didnt do the 4kstuff my ssd is not compatible i think i followe the tutorial in ubuntu but can't change block size.

My drive appear during install when i delete the dsdt Nvme-em-pc or something like that .
And i can't have full acceleration working for my intel hd 630

**Comment by krim404** [comment]
toshiba are compatible with 4k. Seems like yours is 4k already. For GPU acceleration please open a new ticket
