### ISSUE TITLE
No boot with your files

### ISSUE THREAD

**Issue by ghost** [wmchris/DellXPS15-9560-OSX#5]
Hi I follow your Guide with everythings setup properly, but when i'm trying to boot nothing happended.

I did everything 4k patch, replace config.plist remove all things regarding hackNvme..
I try to use OsxAptioFixDrv2 but nothing happended
I thinks that's a problem in DRIVERS64UEFI 
See the pictures (I try to run it in safe mode but normal modd is the same just without the line "safe mode"

If you can help us ? Thanks

![img_20170510_235825](https://cloud.githubusercontent.com/assets/26435962/25923374/7d595e24-35dd-11e7-851c-82ef5fdf7632.jpg)

**Comment by krim404** [comment]
you already posted this issue on insanelymac, but in the wrong thread (9550 vs 9560). 
Because of the other questions asked from you it seems like it worked in the past. So redo the process from step 1.

And as i said in the other ticket: this is not a free support for your computer. This repository is just filled with files which are known to work on the 9560. If you cant get it to work you should try your own files or abandon the project OSX on your machine.
